name: Generate PDF

on: 
  push:
    branches:
      - 'main'
  workflow_dispatch:
  
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build PDFs
        run: |
          ./generatePdfs.sh uebungsanleitungen_liste/
        
      - name: Publish PDF
        uses: actions/upload-artifact@v4
        with:
          name: Uebungsanleitungen
          path: uebungsanleitungen_liste/**/*.pdf
